### ISSUE TITLE
Security schemes

### ISSUE THREAD

**Issue by alex-zywicki** [dedoussis/asynction#110]
Hi @dedoussis,

I noticed you listed implementing security schemes as a TODO item in your README.
Do you have any current design plans for implementing security schemes?
What would be needed to help move this feature along?

My use case for `asynction` would involve an `oauth2` based security scheme.

I am currently using `connexion`'s `oauth2` `application` flow and would be aiming for something similar with `asynction`.

**Comment by alex-zywicki** [comment]
@dedoussis I don't think I fully understand how the security schemes would be useful in a real world example. How do the security schemes map back to individual channels or messages on a channel. Or is the security only applied to access to the server itself. Would it be possible to allow users with a the correct scopes to access/use additional channels or messages than others who do not have said scope?

With API's I have written using connexion I tend to have the same "read", "write" scheme you show in your example with the read scope attached to http "GET" routes and the write attached to "PUT, POST, and DELETE" routes.

How would I do something similar?

**Comment by dedoussis** [comment]
@alex-zywicki The authentication/authorization should happen upon establishing a Socket.IO connection. On Socket.IO, a connection is established on the namespace/channel level. By default a Socket.IO client will use a single connection when connecting to the same server (even if it connects to multiple namespaces of that server). However, it is possible for the client to use the [forceNew](https://socket.io/docs/v4/client-initialization/#forceNew) connection param, and force a separate connection per namespace. Would suggest you have a look in [this paragraph](https://dedouss.is/posts/2021-07-14-documenting-socketio-part-2.html#channels) of my article for some extra background on this.

Based on the above, there are 2 possible scenarios:
1. The client does not use the `forceNew` param. In this case there is a connection on the server level (rather than the namespace level), and can be described by the existing security schemes of the specification (see my comment above).
2. The client does use the `forceNew` param, when connecting to multiple namespaces. In this case the security schemes would need to be defined at the channel level, rather than the server, and this is something that is not allowed by the current version of AsyncAPI. So you're right. We would need to propose an RFC for the specification and in the meantime we would need to come up with some a [specification extension](https://www.asyncapi.com/docs/specifications/v2.2.0#specificationExtensions).


Bear in mind that there is no need to include security on the message level, since authn/authz can only happen upon connection.

**Comment by dedoussis** [comment]
Thanks for the contribution @alex-zywicki! This functionality has been released as part of version `0.5.0`. Closing the issue.
