### ISSUE TITLE
python3.6 support

### ISSUE THREAD

**Issue by alex-zywicki** [dedoussis/asynction#130]
Is there a practical reason why python3.6 is not supported? My intended use case for asynction would wind up deployed on a Red Hat linux system (RHEL7, and RHEL8) which come with python 3.6.8 as the system python. In my case it would be tricky to install a newer python for numerous reasons.

What would it take to support python3.6?

**Comment by alex-zywicki** [comment]
I did some quick testing and it looks like the main factor may be dependencies. I know at least `svarog` does not seem to support python3.6

**Comment by dedoussis** [comment]
@alex-zywicki I would be keen to avoid supporting 3.6.x. It's now been 5 years since the release of python 3.6, and there have been 4 minor releases since then. I feel that this is going to impede asynction's progress, as it will add overhead in terms of dependency management. One of the dependencies that does not support python3.6 is svarog as you suggested, which could be replaced by dataclasses-json. However, dataclasses are also not natively supported by python3.6 so we will need to explicitly install [`dataclasses`](https://pypi.org/project/dataclasses/) too. Python3.7 is also adding additional overhead, by forcing us to install `typing-extensions` and `importlib-metadata`, so I imagine this will only be worse for python3.6.

**Comment by alex-zywicki** [comment]
@dedoussis I have managed to upgrade my system to python3.9 so this issue can be closed.

**Comment by dedoussis** [comment]
@alex-zywicki Thanks a lot for the compromise!
